stages:
  - test

variables:
  DB: "mysqli"
  MYSQL_ROOT_PASSWORD: "superrootpass"
  TRAVIS_BUILD_DIR: "$CI_PROJECT_DIR"
  MOODLE_DIR: "/var/www/html/moodle"
  # If we want to ignore some templates, provide them here.
  #MUSTACHE_IGNORE_NAMES: "<file>.mustache, <file2>.mustache, ..., <filen>.mustache"
  PLUGIN: 'block_coupon'
  PATHNAME: 'blocks/coupon'
  REPOURL: 'https://github.com/sebsoftnl/moodle-block_coupon'
  REPOSYS: 'git'
  # Moodle auto format = 0, Markdown = 4, Flat txt = 2
  RELEASENOTEFORMAT: '0'

.job_template: &job_definition
  stage: test
  services:
    - mysql:5.7
  cache:
    paths:
      - $HOME/.composer/cache
      - $HOME/.npm
  allow_failure: false
  image: git.sebsoft.nl:5050/sebsoft/open-source/moodle-cidocker:latest
  script:
    - cd /root/
    - umask u+x
    - cd $CI_PROJECT_DIR/..
    - source /root/.nvm/nvm.sh
    - /root/ci/bin/moodle-plugin-ci install --moodle=$MOODLE_DIR --db-user=root --db-pass=superrootpass --db-host=mysql -vvv
    # Start actually running the CI now.
    - exit_code+=(0)
    - failures=()
    - /root/ci/bin/moodle-plugin-ci phplint || failures+=("PHPLINT")
    - /root/ci/bin/moodle-plugin-ci phpcpd || true
    - /root/ci/bin/moodle-plugin-ci phpmd || failures+=("PHPMD")
    - /root/ci/bin/moodle-plugin-ci codechecker || failures+=("CODECHECKER")
    - /root/ci/bin/moodle-plugin-ci validate || failures+=("VALIDATE")
    - /root/ci/bin/moodle-plugin-ci savepoints || failures+=("SAVEPOINTS")
    - /root/ci/bin/moodle-plugin-ci mustache || failures+=("MUSTACHE")
    - /root/ci/bin/moodle-plugin-ci grunt || failures+=("GRUNT")
    - /root/ci/bin/moodle-plugin-ci phpdoc || failures+=("PHPDOC")
    - /root/ci/bin/moodle-plugin-ci phpunit || failures+=("PHPUNIT")
    - /root/ci/bin/moodle-plugin-ci behat || failures+=("GRUNT")
    # Dump results..
    - for i in ${failures[@]}; do echo "$i -- FAIL"; done;
    - if [ "${#failures[@]}" -gt "0" ]; then echo "${#failures[@]} jobs failed"; exit 1; fi;

Moodle 3.11:
  <<: *job_definition
  variables:
    MOODLE_BRANCH: "MOODLE_311_STABLE"

Moodle 3.10:
  <<: *job_definition
  variables:
    MOODLE_BRANCH: "MOODLE_310_STABLE"
